### ISSUE TITLE
How to replace needed ?

### ISSUE THREAD

**Issue by fansgit** [NixOS/patchelf#103] opened 2016-07-03 00:08 UTC
I tried with `patchelf 0.9` but it seemed not working. Did I abuse it?

```
$ ldd myapp
libXXX.so.1 => not found
...
$ patchelf --replace-needed libXXX.so.1 libXXX.so.2 myapp
$ ldd myapp # old lib not replaced
libXXX.so.1 => not found
...
```

**Comment by ajburley** [comment] 2018-07-08 00:47
Try `readelf -a myapp | grep libXXX.so.1 -B 5` or similar.

You may find the problem is in the .gnu.version_r - if so, there was an issue about that - see #84

Unfortunately, that issue was fixed in April 2016, but the latest release of patchelf (0.9) was in February 2016. You may want to try building patchelf from source and see if that version fixes your issue. (Or, if you are on a supported architecture, try the pre-release build - although I haven't checked myself to see if it contains the fix I mentioned.)

**Comment by domenkozar** [comment] 2020-06-10 08:31
Closing as inactive

**Closed by domenkozar** 2020-06-10 08:31 UTC
