### ISSUE TITLE
stripping debug symbols after patchelf corrupting executable

### ISSUE THREAD

**Issue by srahul123** [NixOS/patchelf#145] opened 2018-03-24 15:43 UTC
I ran the following two commands:

> patchelf --set-rpath $myrpath myexe
> strip -g myexe

The second command gives the error _warning: allocated section `.dynsym' not in segment_ . After that, the executable is not usable. If I try to execute it, I get the following error:

> myexec: relocation error: myexec: symbol , version GLIBC_2.2.5 not defined in file libc.so.6 with link time reference

_myexec_ works fine before I do a _strip -g_ . So, I am not sure if this is a problem with _patchelf_ or with _strip_.

**Comment by bchallenor** [comment] 2018-03-27 07:42
Came here to report the same. I'm trying to package the Android NDK, which requires patching the RPATH of clang to include ncurses, but patchelf followed by strip results in corruption of the binary. Currently working around this with `dontStrip = true`.

**Comment by mhsmith** [comment] 2018-04-16 21:04
Possible duplicate of #10.

**Comment by coldeasy** [comment] 2019-11-29 14:37
I see the same issue with [auditwheel](https://github.com/pypa/auditwheel) which sets the rpath

```bash
$ ldd libssl-a65b360f.so.0.9.8e
        linux-vdso.so.1 (0x00007ffec32cd000)
        libgssapi_krb5-174f8956.so.2.2 => not found
        libkrb5-fb0d2caa.so.3.3 => not found
        libcom_err-beb60336.so.2.1 => not found
        libk5crypto-622ef25b.so.3.1 => not found
        libcrypto-de69073a.so.0.9.8e => not found
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f8829deb000)
        libz-a147dcb0.so.1.2.3 => not found
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f8829c24000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f882a097000)
$ patchelf --force-rpath --set-rpath '$ORIGIN/.libspycurl' libssl-a65b360f.so.0.9.8e
$ ldd libssl-a65b360f.so.0.9.8e
        linux-vdso.so.1 (0x00007ffcf8ded000)
        libgssapi_krb5-174f8956.so.2.2 => /home/.libspycurl/libgssapi_krb5-174f8956.so.2.2 (0x00007ff7c5fbb000)
        libkrb5-fb0d2caa.so.3.3 => /home/.libspycurl/libkrb5-fb0d2caa.so.3.3 (0x00007ff7c5d08000)
        libcom_err-beb60336.so.2.1 => /home/.libspycurl/libcom_err-beb60336.so.2.1 (0x00007ff7c5b05000)
        libk5crypto-622ef25b.so.3.1 => /home/.libspycurl/libk5crypto-622ef25b.so.3.1 (0x00007ff7c58da000)
        libcrypto-de69073a.so.0.9.8e => /home/.libspycurl/libcrypto-de69073a.so.0.9.8e (0x00007ff7c556a000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007ff7c552a000)
        libz-a147dcb0.so.1.2.3 => /home/.libspycurl/libz-a147dcb0.so.1.2.3 (0x00007ff7c5315000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007ff7c514e000)
        libkrb5support-d7ce89d4.so.0.1 => /home/.libspycurl/libkrb5support-d7ce89d4.so.0.1 (0x00007ff7c4f43000)
        libkeyutils-1-ff31573b.2.so => /home/.libspycurl/libkeyutils-1-ff31573b.2.so (0x00007ff7c4d40000)
        libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007ff7c4d25000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007ff7c6466000)
        libselinux-cf8f9094.so.1 => /home/.libspycurl/libselinux-cf8f9094.so.1 (0x00007ff7c4b09000)
        libsepol-b4f5b513.so.1 => /home/.libspycurl/libsepol-b4f5b513.so.1 (0x00007ff7c48c1000)

$ strip libssl-a65b360f.so.0.9.8e
$ ldd libssl-a65b360f.so.0.9.8e
        not a dynamic executable
```

**Comment by domenkozar** [comment] 2020-06-04 09:51
This is fixed in master, please reopen if the issue persists.

**Closed by domenkozar** 2020-06-04 09:51 UTC

**Comment by br1ght3n** [comment] 2020-11-26 11:46
> This is fixed in master, please reopen if the issue persists.

issuse still persists.I build patchelf using the newest master code.  
`
patchelf --add-needed my.so myelf
`
elf can work.  
but after strip it
`
strip -g myelf
`
get print info _strip: sttYKY4c: warning: allocated section `.dynstr' not in segment_   and elf can not work correctly,if i run the elf,
here the output:

```
./myelf --version
./myelf: ./myelf: no version information available (required by ./myelf)
./myelf: ./myelf: no version information available (required by ./myelf)
./myelf: ./myelf: no version information available (required by ./myelf)
./myelf: ./myelf: no version information available (required by ./myelf)
./myelf: ./myelf: no version information available (required by ./myelf)
./myelf: ./myelf: no version information available (required by ./myelf)
./myelf: ./myelf: no version information available (required by ./myelf)
./myelf: ./myelf: no version information available (required by ./myelf)
./myelf: ./myelf: no version information available (required by ./myelf)
./myelf: symbol lookup error: ./myelf: undefined symbol: , version
```

**Comment by domenkozar** [comment] 2020-11-26 11:50
Can you upload myelf?

**Comment by br1ght3n** [comment] 2020-11-26 12:05
ok.here is myelf file.

[myelf.zip](https://github.com/NixOS/patchelf/files/5602793/myelf.zip)
