### ISSUE TITLE
Patchelf breaks strip

### ISSUE THREAD

**Issue by jakobrs** [NixOS/patchelf#196] opened 2020-03-22 12:46 UTC
@grahamc

When packaging libtas, I noticed some weird result where stripping *after* patchelf makes the executable segfault.

The relevant derivation is [here](https://github.com/jakobrs/libTAS/blob/here/libTAS.nix)

Build results: [stuffs.tar.gz](https://github.com/NixOS/patchelf/files/4365221/stuffs.tar.gz). `b` should segfault; the others should not.

**Comment by probonopd** [comment] 2020-03-22 13:03
Duplicate of https://github.com/NixOS/patchelf/issues/145?

**Comment by jakobrs** [comment] 2020-03-22 13:13
Could very well be. There's a different error though, and I don't get any warnings. See also #110.

There's more context in the IRC logs.

**Comment by domenkozar** [comment] 2020-06-02 09:42
This is fixed in patchelf 0.10, but nixpkgs still uses 0.9. See https://github.com/NixOS/nixpkgs/issues/69213

**Closed by domenkozar** 2020-06-02 09:42 UTC
