### ISSUE TITLE
patchelf fails on big files

### ISSUE THREAD

**Issue by varyshare** [NixOS/patchelf#305] opened 2021-08-24 13:50 UTC
**Describe the bug**

patchelf fails with `patchelf: maximum file size exceeded` on `742076728` .so file

**Steps To Reproduce**

1. Download https://developer.nvidia.com/compute/machine-learning/cudnn/secure/8.0.5/10.1_20201106/cudnn-10.1-linux-x64-v8.0.5.39.tgz (might need creation of account)
2. Supply it as source into `<nixpkgs>` cdd derivation

3. on execution of `patchelf --set-rpath /nix/store/3vkxrsrgvnx62shi42hcrsic3wj0s4bq-gcc-9.2.0-lib/lib:$ORIGIN/` it will fail with
`patchelf: maximum file size exceeded`

**Expected behavior**

patch file

**`patchelf --version` output**

`patchelf 0.13.20210805.a949ff2`
0.12 from `master` failed too, I tried to upgrade `patchelf` expecting the bug is already fixed, but no

**Additional context**

**Comment by varyshare** [comment] 2021-08-24 13:51
https://github.com/NixOS/patchelf/pull/256

**Comment by Mic92** [comment] 2021-09-08 09:13
Hopefully fixed by https://github.com/NixOS/patchelf/pull/256
Can you test? @varyshare

**Comment by varyshare** [comment] 2021-09-08 18:40
> Hopefully fixed by #256
> Can you test? @varyshare

No, I just increased `32 * 1024 * 1024` to `128 * 1024 * 1024` and worked around. Dowloading huge file again is difficult

**Comment by domenkozar** [comment] 2021-09-13 16:55
@varyshare how can we reproduce your error? It's unlikely you get the same error since it was removed from source.

**Closed** 2021-11-27 10:01 UTC
Labels: bug
