### ISSUE TITLE
Assertion `strTabAddr == rdi(shdrDynStr.sh_addr)' failed.

### ISSUE THREAD

**Issue by carlorosati** [NixOS/patchelf#116] opened 2017-02-28 15:39 UTC
```
% patchelf --print-rpath /opt/google/chrome/libwidevinecdm.so                                 ldt-1467434 1135
patchelf: patchelf.cc:1046: void ElfFile<Elf_Ehdr, Elf_Phdr, Elf_Shdr, Elf_Addr, Elf_Off, Elf_Dyn, Elf_Sym>::modifyRPath(ElfFile<Elf_Ehdr, Elf_Phdr, Elf_Shdr, Elf_Addr, Elf_Off, Elf_Dyn, Elf_Sym>::RPathOp, std::string) [with Elf_Ehdr = Elf64_Ehdr; Elf_Phdr = Elf64_Phdr; Elf_Shdr = Elf64_Shdr; Elf_Addr = long unsigned int; Elf_Off = long unsigned int; Elf_Dyn = Elf64_Dyn; Elf_Sym = Elf64_Sym; std::string = std::basic_string<char>]: Assertion `strTabAddr == rdi(shdrDynStr.sh_addr)' failed.
zsh: abort      patchelf --print-rpath /opt/google/chrome/libwidevinecdm.so
```

**Comment by edolstra** [comment] 2017-02-28 16:17
Dupe of https://github.com/NixOS/nixpkgs/issues/22333.

**Closed by edolstra** 2017-02-28 16:17 UTC
